repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff
      args: ['--fix']
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
    - id: black
      language_version: python3.10
