import os

CONFIDENCE_CHUNK_SIZE = int(os.getenv(
    'MOKAPOT_CONFIDENCE_CHUNK_SIZE', 1000000))
CHUNK_SIZE_READ_ALL_DATA = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_READ_ALL_DATA', 200000))
CHUNK_SIZE_ROWS_PREDICTION = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_ROWS_PREDICTION', 700000))
CHUNK_SIZE_COLUMNS_FOR_DROP_COLUMNS = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_COLUMNS_FOR_DROP_COLUMNS', 19))
CHUNK_SIZE_ROWS_FOR_DROP_COLUMNS = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_ROWS_FOR_DROP_COLUMNS', 2000000))
