name: PyPI

on:
  release:
    types: [created]

jobs:
  deploy-pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build --sdist --wheel .
          twine upload dist/*

  windows-installer:
    runs-on: windows-latest
    needs: deploy-pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pyinstaller
      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install innosetup -y --allow-unofficial --force
      - name: Run pyinstaller
        run: pyinstaller ./pyinstaller.spec --clean --noconfirm
      - name: Test built exe
        run: dist/mokapot/mokapot.exe --help
      - name: Run Inno Setup
        run: ISCC.exe ./innosetup.iss /DAppVersion=${{  github.ref_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.exe
      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: dist/*.exe
